let books = [
  {
    id: "1",
    author_id: "1",
    title: "indiana jones",
    subtitle: "",
    blanket: "",
    lang: "",
    format_book: "",
    genre: "shit",
    authorId: "1",
    genre: "",
    ISBN: "",
    borrower_id: "",
    borrower_date: "",
    state: ""
  },
  {
    id: "2",
    author_id: "5",
    title: "indiana",
    subtitle: "",
    blanket: "",
    lang: "",
    format_book: "",
    genre: "shit",
    authorId: "1",
    genre: "",
    ISBN: "",
    borrower_id: "",
    borrower_date: "",
    state: ""
  },

  {
    id: "3",
    author_id: "4",
    title: "jones",
    subtitle: "",
    blanket: "",
    lang: "",
    format_book: "",
    genre: "shit",
    ISBN: "",
    borrower_id: "",
    borrower_date: "",
    state: ""
  },

  {
    id: "4",
    author_id: "1",
    title: "flagada jones",
    subtitle: "",
    blanket: "",
    lang: "",
    format_book: "",
    genre: "shit",
    ISBN: "",
    borrower_id: "",
    borrower_date: "",
    state: ""
  },

  {
    id: "5",
    author_id: "2",
    title: "bones",
    subtitle: "",
    blanket: "",
    lang: "",
    format_book: "",
    genre: "shit",
    ISBN: "",
    borrower_id: "",
    borrower_date: "",
    state: ""
  },

  {
    id: "6",
    author_id: "1",
    title: "mabite",
    subtitle: "",
    blanket: "",
    lang: "",
    format_book: "",
    genre: "shit",
    ISBN: "",
    borrower_id: "",
    borrower_date: "",
    state: ""
  },
  {
    id: "7",
    author_id: "2",
    title: "tatatat",
    subtitle: "",
    blanket: "",
    lang: "",
    format_book: "",
    genre: "shit",
    ISBN: "",
    borrower_id: "",
    borrower_date: "",
    state: ""
  },
  {
    id: "8",
    author_id: "2",
    title: "tatatat",
    subtitle: "",
    blanket: "",
    lang: "",
    format_book: "",
    genre: "shit",
    ISBN: "",
    borrower_id: "1",
    borrower_date: "2019-08-12",
    state: ""
  },
  ,
  {
    id: "9",
    author_id: "2",
    title: "tatataratata",
    subtitle: "",
    blanket: "",
    lang: "",
    format_book: "",
    genre: "shit",
    ISBN: "",
    borrower_id: "1",
    borrower_date: "2019-08-12",
    state: ""
  },
];

module.exports = books;
